### ISSUE TITLE
Conversion fails 

### ISSUE THREAD

**Issue by LeonardAukea** [Valassis-Digital-Media/nbconflux#35]
Interesting package. it would be nice if it worked. we are using confluence across the org and it would be awesome if we could share are results like this directly from the notebook.

Unfortunately, it does not work:

`nbconflux path/to/notebook.ipynb https://path/to/page`

traceback: 
```
Traceback (most recent call last):
  File "/Users/laukea/.pyenv/versions/miniconda3-latest/bin/nbconflux", line 10, in <module>
    sys.exit(main())
  File "/Users/laukea/.pyenv/versions/miniconda3-latest/lib/python3.7/site-packages/nbconflux/cli.py", line 57, in main
    extra_labels=args.extra_labels)
  File "/Users/laukea/.pyenv/versions/miniconda3-latest/lib/python3.7/site-packages/nbconflux/api.py", line 56, in notebook_to_page
    exporter = ConfluenceExporter(c)
  File "/Users/laukea/.pyenv/versions/miniconda3-latest/lib/python3.7/site-packages/nbconflux/exporter.py", line 100, in __init__
    self.server, self.page_id = self.get_server_info(self.url)
  File "/Users/laukea/.pyenv/versions/miniconda3-latest/lib/python3.7/site-packages/nbconflux/exporter.py", line 149, in get_server_info
    page_id = int(segs[5])
ValueError: invalid literal for int() with base 10: 'create'
```

**Comment by LeonardAukea** [comment]
This was due to the path   to the confluence page. my fault...you can close this issue. The authentication is failing though. even if I'm using the correct user and pass.
